stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deploy  # This must match the tag on your GitLab Runner
  only:
    - main    # Trigger only when pushing to main
  script:
    - echo "Installing SSH client..."
    - apt-get update -y && apt-get install -y openssh-client

    - echo "Starting SSH agent..."
    - eval $(ssh-agent -s)

    - echo "Adding private key to SSH agent..."
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "Adding server to known_hosts..."
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - echo "SSH into server and deploy..."
    - ssh $DEPLOY_USER@$DEPLOY_HOST <<EOF
        cd $DEPLOY_PATH
        git pull origin main
        docker-compose down
        docker-compose up -d --build
      EOF
